.eslintrc.json, .husky/commit-msg, .husky/pre-commit, .lintstagedrc.js, .vscode/extensions.json, commitlint.config.js, package-lock.json, package.json
Install husky, lint-staged, commit lint, eslint, prettier and add hooks to lint and detect bad commit messages.
Add recommended vscode extensions
=> ci: install husky, add pre-commit hooks

.github/workflows/chromatic.yml, .storybook/main.js, .storybook/preview.js, components/Button/Button.tsx, package-lock.json, package.json, postcss.config.js, prettier.config.js, styles/globals.css, tailwind.config.js
install tailwind
Close #16
reconfigure storybook to accept tailwind
Fix chromatic deployment workflow to use npm and use setup node github action for caching
=> feat: install tailwind

.github/workflows/cleanup_preview.yml
fix bug in cleaning up db workflows
=> ci: cleanup db

.github/workflows/preview.yml, .github/workflows/production.yml
Fix ignored branch in preview deployments and main branch in production
deployments.
=> ci: fix branch in deployments

components/Navbar/NavItem.tsx, components/Navbar/Navbar.css, components/Navbar/Navbar.stories.tsx, components/Navbar/Navbar.tsx, pages/_app.tsx
- UI: create navbar component
Close #36
=> feat(UI): create navbar

components/Footer/Footer.stories.tsx, components/Footer/Footer.tsx
- UI: create footer component
- Close #37
=> feat(UI): Footer

components/UserProfile/UserProfileForm.stories.tsx, components/UserProfile/UserProfileForm.tsx
=> Creat User Profile Component

graphql/schema.graphql, graphql/types/Game.ts, graphql/types/index.ts, prisma/migrations/20221109120117_game/migration.sql, prisma/schema.prisma
=> feat(API,DB): query all available games

graphql/schema.graphql, graphql/types/User.ts
=> feat(API): api update user profile

components/View/View-source.stories.tsx, components/View/View-source.tsx, package-lock.json, package.json, pages/_app.tsx
=> feat(UI): add show available games components

components/GameRegister/GameRegister.tsx
=> feat: add UI register game

prisma/migrations/20221115102828_add_booking_table/migration.sql, prisma/schema.prisma
=> feat: create booking table

graphql/schema.graphql, graphql/types/Booking.ts, graphql/types/index.ts, prisma/schema.prisma
=> feat: expose GraphQL query to create new ticket

.github/workflows/vercel.yml
=> ci: fix schema name in db setup

prisma/migrations/20221117074852_time_slot/migration.sql, prisma/schema.prisma
=> feat(db): add Time Slot table

components/TicketForm/TicketFormBooking.stories.tsx, components/TicketForm/TicketFormBooking.tsx
=> feat(UI): create ticket book form

components/GameRegister/GameRegister.tsx, components/GameRegister/index.ts, pages/create-game.tsx
=> Create game register page

graphql/types/User.ts
=> feat(API): authorize user to update profile

components/Booking/BookingForm.stories.tsx, components/Booking/BookingForm.tsx
=> feat: add booking form

components/SignUp/SignUpForm.tsx, pages/signup.tsx
=> feat: add user and game orner role to sign up page

components/TicketForm/TicketFormBooking.tsx, graphql/types/Game.ts, pages/time-slot.tsx
=> feat(api): display timeSlot page

pages/create-game.tsx
=> feat(ui): route to game info page on game created

graphql/types/Game.ts, lib/apollo.ts, pages/create-game.tsx
=> feat: authorize register game only by store owner

components/UserProfile/UserProfileView.stories.tsx, components/UserProfile/UserProfileView.tsx, pages/edit-profile.tsx, pages/index.tsx
=> feat(UI): editable non-editable profile
